# Generated by Django 4.1.4 on 2022-12-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
